---
fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.16.0"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall"
  symlinks:
    pacemaker: "#{source_dir}"
