# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   Gather resource parameters and their values
#
#
Puppet::Functions.create_function(:'pacemaker::pacemaker_resource_parameters') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    parameters = {}
    args.flatten.each_slice(2) do |key, value|
      if value.nil? and key.is_a? Hash
        parameters.merge! key
      else
        next if key.nil?
        next if key == ''
        next if value.nil?
        next if value == ''
        next if value == :undef
        key = key.to_s
        parameters.store key, value
      end
    end
    parameters
  
  end
end
